// Database med spørsmål
// Vi legger den på 'window' objektet for å være sikker på at script.js finner den.
window.rawQuestions = [
    // --- MODULE 1: Intro & Python ---
    { q: "What is the primary distinction between Machine Learning and traditional programming?", options: ["ML is faster", "ML learns rules from data instead of explicit programming", "ML uses Python", "ML creates databases"], a: 1, exp: "Traditional programming relies on hard-coded rules, while ML infers rules from data." },
    { q: "Which type of learning deals with labeled data (Input-Output pairs)?", options: ["Unsupervised Learning", "Reinforcement Learning", "Supervised Learning", "Clustering"], a: 2, exp: "Supervised learning trains on known outcomes (labels)." },
    { q: "Which library is specifically designed for data manipulation and DataFrames?", options: ["NumPy", "Pandas", "Scikit-Learn", "SciPy"], a: 1, exp: "Pandas provides the DataFrame structure essential for data analysis." },
    { q: "What is 'NumPy' primarily used for?", options: ["Web development", "N-dimensional arrays and numerical computing", "Visualization", "Natural Language Processing"], a: 1, exp: "NumPy is the foundation for numerical computing in Python." },
    { q: "Which Scikit-learn function is used to divide data into training and validation sets?", options: ["divide_data()", "train_test_split()", "split_validation()", "make_groups()"], a: 1, exp: "train_test_split() is the standard function for creating training and testing sets." },
    { q: "What is Reinforcement Learning characterized by?", options: ["Clustering unlabeled data", "An agent learning via rewards/penalties", "Predicting continuous values", "Text processing"], a: 1, exp: "It involves an agent acting in an environment to maximize a cumulative reward." },
    { q: "Which of these is an example of Unsupervised Learning?", options: ["Spam Detection", "House Price Prediction", "Customer Segmentation (Clustering)", "Digit Recognition"], a: 2, exp: "Segmentation finds groups in data without pre-existing labels." },
    { q: "What does `Scikit-learn` primarily provide?", options: ["Deep Learning layers", "Standard ML algorithms (SVM, KNN, Regression)", "Game development tools", "Database management"], a: 1, exp: "It is the go-to library for classical machine learning algorithms." },

    // --- MODULE 2: Math for AI ---
    { q: "What does a Vector represent in ML?", options: ["A single number", "A feature array with magnitude and direction", "A 2D table", "A timestamp"], a: 1, exp: "Vectors are 1D arrays representing data points or features." },
    { q: "If the Dot Product of two vectors is 0, they are:", options: ["Parallel", "Identical", "Orthogonal (Uncorrelated)", "Opposite"], a: 2, exp: "Zero dot product implies a 90-degree angle between vectors." },
    { q: "What is a Matrix?", options: ["A 1D array", "A 2D array of numbers (Rows x Cols)", "A scalar", "A string of text"], a: 1, exp: "Matrices represent datasets (Rows=Samples, Cols=Features)." },
    { q: "What is the disadvantage of One-Hot Encoding?", options: ["It creates sparse, high-dimensional vectors", "It is too simple", "It cannot represent numbers", "It is lossy"], a: 0, exp: "It results in vectors with many zeros, wasting memory and losing semantic relationships." },
    { q: "What is the goal of PCA (Principal Component Analysis)?", options: ["Increase dimensions", "Dimensionality reduction while preserving variance", "Clustering data", "Classifying images"], a: 1, exp: "PCA reduces variables by finding the principal components (directions of max variance)." },
    { q: "What are Eigenvectors in the context of PCA?", options: ["The magnitude of spread", "The direction of the spread/variance", "The outliers", "The labels"], a: 1, exp: "Eigenvectors point in the direction of the data's spread." },
    { q: "What is Singular Value Decomposition (SVD)?", options: ["A sorting algorithm", "A matrix factorization method", "A type of neural network", "A clustering technique"], a: 1, exp: "SVD decomposes a matrix into three smaller matrices, used in PCA and embeddings." },
    { q: "What is a 'Sparse Vector'?", options: ["A vector with mostly non-zero values", "A vector with mostly zeros", "A vector with negative numbers", "A very short vector"], a: 1, exp: "Vectors from One-Hot Encoding are typically sparse (mostly zeros)." },

    // --- MODULE 3: ML Algorithms ---
    { q: "What is Linear Regression used for?", options: ["Predicting categories", "Predicting continuous values", "Clustering", "Reinforcement"], a: 1, exp: "Linear regression predicts numerical outputs (e.g., temperature, price)." },
    { q: "What is the Cost Function typically used in Linear Regression?", options: ["Accuracy", "MSE (Mean Squared Error)", "Gini Impurity", "Cross-Entropy"], a: 1, exp: "MSE measures the average squared difference between prediction and actual value." },
    { q: "What does 'K' represent in K-Nearest Neighbors (KNN)?", options: ["Number of clusters", "Number of training epochs", "Number of neighbors to vote", "The learning rate"], a: 2, exp: "It determines how many neighbors contribute to the classification decision." },
    { q: "Why is KNN called a 'Lazy Learner'?", options: ["It is slow", "It doesn't learn a model, just stores training data", "It has low accuracy", "It uses simple math"], a: 1, exp: "It performs computation only during prediction, not training." },
    { q: "What is the goal of a Support Vector Machine (SVM)?", options: ["Find the hyperplane with maximum margin", "Find the shortest path", "Group similar items", "Predict probabilities"], a: 0, exp: "SVM maximizes the distance (margin) between the separating hyperplane and the classes." },
    { q: "What is the 'Kernel Trick' in SVM used for?", options: ["Speeding up calculation", "Handling non-linearly separable data", "Reducing data size", "Removing outliers"], a: 1, exp: "It transforms data into higher dimensions to make it linearly separable." },
    { q: "What does Entropy measure in Decision Trees?", options: ["Accuracy", "Impurity or Randomness", "Distance", "Computation time"], a: 1, exp: "Decision trees split data to reduce entropy (make nodes purer)." },
    { q: "What is Information Gain?", options: ["The reduction in entropy after a split", "The amount of data collected", "The accuracy of the model", "The speed of the tree"], a: 0, exp: "It measures how well a feature splits the data into classes." },
    { q: "What is a Confusion Matrix?", options: ["A math puzzle", "A table comparing predicted vs actual classifications", "A neural network layer", "A data cleaning tool"], a: 1, exp: "It shows TP, TN, FP, and FN counts." },
    { q: "Formula for Accuracy?", options: ["TP / (TP + FP)", "(TP + TN) / Total", "TP / (TP + FN)", "TP / Total"], a: 1, exp: "The ratio of correct predictions to total predictions." },
    { q: "Which metric is critical for identifying ALL positive cases (e.g., Cancer)?", options: ["Precision", "Recall (Sensitivity)", "Accuracy", "Specificity"], a: 1, exp: "Recall measures the percentage of actual positives correctly identified." },
    { q: "What is K-Means Clustering?", options: ["Supervised classification", "Unsupervised partitioning into K groups", "Regression algorithm", "Dimensionality reduction"], a: 1, exp: "It groups data into K clusters by minimizing distance to centroids." },
    { q: "How do we update centroids in K-Means?", options: ["Move them randomly", "Move them to the mean of assigned points", "Move them to the origin", "Do not move them"], a: 1, exp: "The centroid moves to the average position of all points in its cluster." },
    { q: "What is 'Overfitting'?", options: ["Model is too simple", "Model learns noise/details of training data too well", "Model has low accuracy", "Model is too slow"], a: 1, exp: "The model performs well on training data but poorly on new, unseen data." },

    // --- MODULE 4: Neural Networks ---
    { q: "What is a Perceptron?", options: ["A complex brain", "A mathematical model of a single neuron", "A type of memory", "A clustering method"], a: 1, exp: "It takes inputs, applies weights/bias, and an activation function." },
    { q: "Why are Activation Functions necessary?", options: ["To introduce non-linearity", "To convert data to text", "To initialize weights", "To calculate error"], a: 0, exp: "Without them, a neural network is just a linear regression model." },
    { q: "Which activation function outputs values between 0 and 1?", options: ["ReLU", "Sigmoid", "Tanh", "Linear"], a: 1, exp: "Sigmoid is often used for probabilities." },
    { q: "What is the main advantage of ReLU over Sigmoid?", options: ["It is slower", "It avoids the Vanishing Gradient problem", "It outputs negative numbers", "It is complex"], a: 1, exp: "ReLU does not saturate for positive values, allowing deep networks to learn." },
    { q: "What is Backpropagation?", options: ["Moving inputs forward", "Calculating gradients to update weights", "Testing the model", "Initializing data"], a: 1, exp: "The algorithm that calculates how much each weight contributed to the error." },
    { q: "What does Gradient Descent do?", options: ["Increases the error", "Updates weights to minimize the loss function", "Shuffles the data", "Selects features"], a: 1, exp: "It iteratively adjusts weights to find the minimum of the cost function." },
    { q: "What is an Epoch?", options: ["One batch processed", "One complete pass through the entire dataset", "The learning rate", "Number of layers"], a: 1, exp: "One epoch means the model has seen every sample once." },
    { q: "What is a Batch?", options: ["The whole dataset", "A subset of data processed before updating weights", "A type of error", "A neuron"], a: 1, exp: "Training is often done in batches to save memory and update weights more frequently." },
    { q: "What happens in the Output Layer?", options: ["Feature extraction", "Final prediction/classification", "Data cleaning", "Weight initialization"], a: 1, exp: "It produces the final result (e.g., class probabilities)." },
    { q: "What is the Learning Rate?", options: ["The speed of the CPU", "The step size used in weight updates", "The accuracy of the model", "Number of neurons"], a: 1, exp: "It controls how much the weights change in each step of Gradient Descent." },

    // --- MODULE 5: Deep Learning ---
    { q: "What distinguishes Deep Learning from Shallow Learning?", options: ["Uses Python", "Has multiple hidden layers", "Uses labeled data", "Is unsupervised"], a: 1, exp: "Deep Learning uses deep neural networks with many layers to extract features." },
    { q: "What are CNNs (Convolutional Neural Networks) best at?", options: ["Text analysis", "Image processing (Grid data)", "Financial forecasting", "Clustering"], a: 1, exp: "CNNs preserve spatial structures in images." },
    { q: "What is the purpose of a Convolution Layer?", options: ["Reduce size", "Extract features using filters/kernels", "Flatten data", "Make predictions"], a: 1, exp: "It applies filters to detect edges, textures, and shapes." },
    { q: "What does a Pooling Layer do?", options: ["Increases parameters", "Down-samples (reduces spatial dimensions)", "Changes colors", "Inverts image"], a: 1, exp: "It reduces the size of the feature map, reducing computation and overfitting." },
    { q: "What is the problem with standard RNNs?", options: ["Too fast", "Vanishing Gradient (Short-term memory)", "Too many layers", "Cannot handle text"], a: 1, exp: "Gradients disappear over long sequences, making them forget early inputs." },
    { q: "How does LSTM solve the RNN problem?", options: ["Using Convolution", "Using Gates (Input, Output, Forget)", "Using smaller weights", "Using Sigmoid only"], a: 1, exp: "Gates regulate the flow of information, allowing long-term memory." },
    { q: "What is an Autoencoder?", options: ["A supervised classifier", "An unsupervised network for data compression/reconstruction", "A reinforcement agent", "A regression model"], a: 1, exp: "It learns to encode data into a bottleneck and decode it back." },
    { q: "What is the 'Bottleneck' in an Autoencoder?", options: ["The input layer", "The compressed latent space", "The output layer", "The loss function"], a: 1, exp: "The layer with the fewest neurons, forcing the network to learn efficient representations." },
    { q: "What is the 'Flatten' layer used for?", options: ["Smoothing images", "Converting 2D/3D maps to 1D vectors", "Removing noise", "Clustering"], a: 1, exp: "It prepares spatial data for the final fully connected layers." },
    { q: "What is a 'Tensor' in TensorFlow?", options: ["A flow chart", "A multi-dimensional array", "A neural network", "A CPU"], a: 1, exp: "Tensors are the fundamental data structure (generalized matrices) in DL." },

    // --- MODULE 6: NLP ---
    { q: "What is Tokenization?", options: ["Translating text", "Splitting text into words/sub-units", "Finding sentiment", "Correcting grammar"], a: 1, exp: "The process of breaking text into individual tokens (words/subwords)." },
    { q: "What is Stemming?", options: ["Removing stop words", "Reducing words to their root form (cutting suffixes)", "Counting words", "Vectorizing text"], a: 1, exp: "e.g., 'Fishing' -> 'Fish'." },
    { q: "What are Stop Words?", options: ["Rare words", "Common words with little meaning (the, is, a)", "Verbs", "Nouns"], a: 1, exp: "They are often removed to focus on meaningful words." },
    { q: "What does TF-IDF measure?", options: ["Total word count", "Word importance based on frequency in doc vs corpus", "Sentence length", "Grammar accuracy"], a: 1, exp: "It highlights words that are unique to a specific document." },
    { q: "What is a Word Embedding (e.g., Word2Vec)?", options: ["A list of words", "A dense vector representation capturing semantic meaning", "A sparse vector", "A database"], a: 1, exp: "It maps words to vectors where similar words are close in space." },
    { q: "What is the core mechanism of Transformers (BERT/GPT)?", options: ["Convolution", "Self-Attention", "Recurrence", "Pooling"], a: 1, exp: "Attention allows the model to weigh the importance of all words relative to each other." },
    { q: "What is Hugging Face?", options: ["A robot", "A platform/library for pre-trained NLP models", "An algorithm", "A programming language"], a: 1, exp: "It hosts thousands of Transformer models and datasets." },
    { q: "What is Transfer Learning in NLP?", options: ["Copying text", "Using a pre-trained model and fine-tuning it on a new task", "Translating languages", "Learning from scratch"], a: 1, exp: "It saves massive amounts of time and compute by starting with a knowledgeable model." },
    { q: "What is 'Bag of Words'?", options: ["A shopping list", "Representing text by word frequency, ignoring order", "A deep learning model", "A tokenization method"], a: 1, exp: "It creates a vector based on word counts, losing context." },
    { q: "What is 'Sentiment Analysis'?", options: ["Predicting the next word", "Classifying the emotional tone of text", "Summarizing text", "Translating text"], a: 1, exp: "Determining if text is positive, negative, or neutral." }
];